name: "Build and lint"
on: push

jobs:
  web-ext:
    runs-on: ubuntu-latest
    name: "web-ext Build and Lint"
    strategy:
      matrix:
        command: ["build", "lint"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build extension
        uses: ./.github/actions/build
      - name: "web-ext ${{ matrix.command }}"
        uses: kewisch/action-web-ext@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cmd: ${{ matrix.command }}
          source: "./dist"
          channel: listed
  bun-tests:
    name: Bun tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build extension
        uses: ./.github/actions/build
      - name: Run bun tests
        run: bun test --coverage-reporter lcov
        shell: bash
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
